### ISSUE TITLE
Can't download missing beatmaps

### ISSUE THREAD

**Issue by Moniu001** [Piotrekol/CollectionManager#48]
************** 异常文本 **************
System.Net.WebException: 远程服务器返回错误: (403) 已禁止。
   在 System.Net.HttpWebRequest.GetResponse()
   在 System.Net.CookieAwareWebClient.Login(String loginPageAddress, String loginData)
   在 CollectionManagerExtensionsDll.Modules.DownloadManager.OsuDownloader.Login(LoginData loginData)
   在 App.OsuDownloadManager.LogIn(LoginData loginData)
   在 App.OsuDownloadManager.AskUserForSaveDirectoryAndLogin(IUserDialogs userDialogs, ILoginFormView loginForm)
   在 App.SidePanelActionsHandler.DownloadAllMissing(Object sender, Object data)
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by SNMercy** [comment]
I am having a similar problem.  I've tried logging into the osustats collection and reading all previous issues along with the "README.txt", yet nothing seems to indicate why I'm having this error. There's no prompt for choosing a file location to download the maps into.  I simply get an error box with the included text:


System.NotImplementedException: download sources configuration is missing!
   at App.OsuDownloadManager.<>c.<.ctor>b__50_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at App.OsuDownloadManager.AskUserForSaveDirectoryAndLogin(IUserDialogs userDialogs, ILoginFormView loginForm)
   at App.SidePanelActionsHandler.DownloadAllMissing(Object sender, Object data)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Piotrekol** [comment]
You are either getting rate-limited or provided login cookies incorrectly
