### ISSUE TITLE
i can't download beatmaps

### ISSUE THREAD

**Issue by JergenRoss** [Piotrekol/CollectionManager#52]
I installed this app for first time. 

i trying downloading [Ranked maps (2022)](https://osustats.ppy.sh/collection/8761)
i put import collection ```.db/.osdb```, selected location: ```C:\Users\Jhecrose\AppData\Local\osu!\Skins``` and cookie login applied but

but i got error:
```
System.NotImplementedException: download sources configuration is missing!
   at App.OsuDownloadManager.<>c.<.ctor>b__50_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at App.OsuDownloadManager.AskUserForSaveDirectoryAndLogin(IUserDialogs userDialogs, ILoginFormView loginForm)
   at App.BeatmapListingActionsHandler.DownloadBeatmapsManaged(Object sender)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
![Error Download](https://user-images.githubusercontent.com/59808813/155350190-088a82dd-ddf0-44c5-9f2b-04ac343e6379.png)

i tried run as admin but doesn't work for me.
how i do fix download sources configuration is missing?

**Comment by Piotrekol** [comment]
#45
