### ISSUE TITLE
Error trying to install CollectionManager_linux

### ISSUE THREAD

**Issue by osulover9000** [Piotrekol/CollectionManager#60]
```
There was a problem with CollectionManager and it needs to exit, exception text was copied to your clipboard:
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. File not found.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at App.Initalizer.Run(String[] args)
   at App.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```
and then when I click "Ok" another window pops up with "Show Details"

```
Unhandled exception: 0xe0434352 in 32-bit code (0x7b010be6).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:006b GS:0063
 EIP:7b010be6 ESP:0063e0b4 EBP:0063e128 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:0063e0c0 EBX:00000000 ECX:00000010 EDX:0063e194
 ESI:e0434352 EDI:0049a2d8
Stack dump:
0x0063e0b4:  018c98c8 00000000 00000000 e0434352
0x0063e0c4:  00000001 00000000 7b010be6 00000005
0x0063e0d4:  80070002 00000000 00000000 00000000
0x0063e0e4:  79140000 0063e104 791f1f44 00000059
0x0063e0f4:  00000000 0063e194 001d24b0 02000059
0x0063e104:  0063e114 79150559 0063e11c 02000059
Backtrace:
=>0 0x7b010be6 EntryPoint+0xffffffff() in kernelbase (0x0063e128)
  1 0x7926fcc8 EntryPoint+0x20f0f() in clr (0x0063e1c8)
  2 0x792b6647 EntryPoint+0x6788e() in clr (0x0063e204)
  3 0x7940917f AttachProfiler+0xe9bd6() in clr (0x0063e280)
  4 0x791ff296 EntryPoint+0xffffffff() in clr (0x0063e2d0)
  5 0x791ff3d0 EntryPoint+0xffffffff() in clr (0x0063e338)
  6 0x7981640d EntryPoint+0xffffffff() in clrjit (0x0063e35c)
  7 0x79826f45 EntryPoint+0xffffffff() in clrjit (0x0063ea50)
  8 0x79812d28 EntryPoint+0xffffffff() in clrjit (0x0063eacc)
  9 0x79812e58 EntryPoint+0xffffffff() in clrjit (0x0063eae4)
  10 0x79812ea2 EntryPoint+0xffffffff() in clrjit (0x0063eb00)
  11 0x798132a2 EntryPoint+0xffffffff() in clrjit (0x0063eb3c)
  12 0x79813396 EntryPoint+0xffffffff() in clrjit (0x0063ebac)
  13 0x798134c9 EntryPoint+0xffffffff() in clrjit (0x0063ec88)
  14 0x79815e4b EntryPoint+0xffffffff() in clrjit (0x0063ecac)
  15 0x79201121 EntryPoint+0xffffffff() in clr (0x0063ed14)
  16 0x792011ad EntryPoint+0xffffffff() in clr (0x0063ed5c)
  17 0x792011f3 EntryPoint+0xffffffff() in clr (0x0063edc4)
  18 0x79200fc8 EntryPoint+0xffffffff() in clr (0x0063f180)
  19 0x792876c3 EntryPoint+0x3890a() in clr (0x0063f260)
  20 0x79287870 EntryPoint+0x38ab7() in clr (0x0063f2d0)
  21 0x7916211d EntryPoint+0xffffffff() in clr (0x0063f334)
  22 0x01560362 (0x0063f34c)
  23 0x04332847 (0x0063f384)
  24 0x791421bb EntryPoint+0xffffffff() in clr (0x0063f394)
  25 0x79164bf2 EntryPoint+0xffffffff() in clr (0x0063f410)
  26 0x79164d94 EntryPoint+0xffffffff() in clr (0x0063f550)
  27 0x79164dc9 EntryPoint+0xffffffff() in clr (0x0063f56c)
  28 0x79164de9 EntryPoint+0xffffffff() in clr (0x0063f584)
  29 0x792b95db EntryPoint+0x6a822() in clr (0x0063f6e8)
  30 0x792ecdd8 EntryPoint+0x9e01f() in clr (0x0063f950)
  31 0x792ecbec EntryPoint+0x9de33() in clr (0x0063fe34)
  32 0x792ecfe1 EntryPoint+0x9e228() in clr (0x0063fe88)
  33 0x792ecee2 EntryPoint+0x9e129() in clr (0x0063fed4)
  34 0x792de1f0 EntryPoint+0x8f437() in clr (0x0063ff0c)
  35 0x603b55ab EntryPoint+0x2032() in mscoreei (0x0063ff18)
  36 0x79007f16 EntryPoint+0x50c1() in mscoree (0x0063ff28)
  37 0x79004de3 EntryPoint+0x1f8e() in mscoree (0x0063ff48)
  38 0x7bc567f7 EntryPoint+0xffffffff() in ntdll (0x0063ff5c)
  39 0x7bc56a50 EntryPoint+0xffffffff() in ntdll (0x0063ffec)
0x7b010be6 EntryPoint+0xffffffff in kernelbase: subl	$4,%esp
Modules:
Module	Address			Debug info	Name (32 modules)
PE	  400000-  42c000	Deferred        app
PE	  fe0000- 1446000	Deferred        ole32
PE	 47c0000- 47ea000	Deferred        zlib1
PE	5e0d0000-5e17a000	Deferred        diasymreader
PE	603b0000-60416000	Export          mscoreei
PE	60930000-60940000	Deferred        nlssorting
PE	61740000-61832000	Deferred        advapi32
PE	61940000-61b21000	Deferred        wininet
PE	62fc0000-631d3000	Deferred        rpcrt4
PE	63480000-6349b000	Deferred        version
PE	63bc0000-63c04000	Deferred        shcore
PE	64a40000-64b29000	Deferred        shlwapi
PE	64ec0000-652b9000	Deferred        oleaut32
PE	68500000-68640000	Deferred        combase
PE	6a280000-6a4cd000	Deferred        msvcrt
PE	6bc00000-6bc99000	Deferred        sechost
PE	6bcc0000-6be60000	Deferred        setupapi
PE	6c9c0000-6cf59000	Deferred        gdi32
PE	6ed00000-6f389000	Deferred        user32
PE	70940000-70994000	Deferred        mpr
PE	70b40000-70df9000	Deferred        ucrtbase
PE	71200000-71251000	Deferred        imm32
PE	79000000-7904a000	Export          mscoree
PE	79060000-7911e000	Deferred        msvcr100_clr0400
PE	79140000-797b0000	Export          clr
PE	79810000-79870000	Export          clrjit
PE	7b000000-7b348000	Dwarf           kernelbase
PE	7b600000-7b929000	Deferred        kernel32
PE	7bc00000-7bea9000	Dwarf           ntdll
PE	f69d0000-f69d6000	Deferred        ws2_32
PE	f6a10000-f72e2000	Deferred        shell32
PE	f7670000-f7674000	Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000050    0
	00000064    0
	00000084    0
	0000009c    0
	000000b8    0
	000000d0    0
00000044 svchost.exe
	00000048    0
	00000054    0
	00000058    0
0000005c winedevice.exe
	00000060    0
	00000068    0
	0000006c    0
	00000070    0
00000074 plugplay.exe
	00000078    0
	00000088    0
	0000008c    0
	00000090    0
	000000ac    0
0000007c explorer.exe
	00000080    0
	000000bc    0
	000000c0    0
00000094 winedevice.exe
	00000098    0
	000000a0    0
	000000a4    0
	000000a8    0
	000000b4    0
000000c8 rpcss.exe
	000000cc    0
	000000d8    0
	000000dc    0
	000000e0    0
	000000e4    0
	000000e8    0
00000120 (D) C:\Program Files\Collection Manager\App.exe
	00000124    0 <==
	00000128    0
	0000012c    2
	00000130    0
	0000013c    0
System information:
    Wine build: wine-6.0.3 (Ubuntu 6.0.3~repack-1)
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 5.16.19-76051619-generic

```
No idea how to fix this. I'm on Pop!_OS 22.04, wine version 6.0.3.

**Comment by thedefaultbox** [comment]
Having the same issue, I am also on Pop!_OS 22.04.
