### ISSUE TITLE
System.IO.EndOfStreamException: Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by X3n0nP0w3r3d** [Piotrekol/CollectionManager#77]
I installed the latest version of the program (1.0.236) and tried setting the osu! folder to another directory since I store my beatmaps separately, containing these only:
![image](https://github.com/Piotrekol/CollectionManager/assets/38383491/3b2f1d8f-14f6-46d7-adf6-2a77b1a4fc6a)

Directory text becomes stuck as "..."
![image](https://github.com/Piotrekol/CollectionManager/assets/38383491/a2b8f27c-56b6-449b-84c8-b6ca1c56a528)

Clicking any button on this menu will throw the error shown below (happens for every button):
![image](https://github.com/Piotrekol/CollectionManager/assets/38383491/9a96ed6d-6787-47b3-9ca8-e607a822dd6f)

```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at CollectionManager.Modules.FileIO.OsuDb.OsuDatabaseLoader.DatabaseContainsData(IProgress`1 progress)
   at CollectionManager.Modules.FileIO.OsuDb.OsuDatabaseLoader.LoadDatabase(String fullOsuDbPath, IProgress`1 progress, CancellationToken cancellationToken)
   at CollectionManager.Modules.FileIO.OsuDb.LOsuDatabaseLoader.LoadDatabase(String fullOsuDbPath, IProgress`1 progress, CancellationToken cancellationToken)
   at App.Presenters.Controls.StartupPresenter.LoadDatabase(CancellationToken cancellationToken)
   at App.Presenters.Controls.StartupPresenter.<Run>b__14_0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at App.Presenters.Controls.StartupPresenter.<_view_StartupDatabaseOperation>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

I have tried uninstalling, reinstalling but it will automatically default to searching the bugged directory.

Any ideas on what's causing the issue?

**Comment by Piotrekol** [comment]
Your first screenshot shows a directory containing dummy 0KB osu!.db & scores.db files. while scores.db is fine(it will fail silently), osu!.db is not, and you need to replace it with one created by osu.

**Comment by X3n0nP0w3r3d** [comment]
Thanks, that seemed to have fixed it :)
